const router = require("express").Router();
const c = require("../controllers/adminController");
const { protect, adminOnly } = require("../middleware/auth");
const auth = [protect, adminOnly];
router.get("/dashboard", ...auth, c.dashboard);
router.get("/users", ...auth, c.getUsers);
router.get("/users/:id", ...auth, c.getUser);
router.patch("/users/:id/toggle", ...auth, c.toggleUser);
router.get("/users/:id/records", ...auth, c.getUserRecords);
router.get("/system/quests", ...auth, c.getSystemQuests);
router.post("/system/quests", ...auth, c.createSystemQuest);
router.patch("/system/quests/:id", ...auth, c.updateSystemQuest);
router.delete("/system/quests/:id", ...auth, c.deleteSystemQuest);
router.get("/system/shop", ...auth, c.getSystemShop);
router.post("/system/shop", ...auth, c.createSystemShop);
router.patch("/system/shop/:id", ...auth, c.updateSystemShop);
router.delete("/system/shop/:id", ...auth, c.deleteSystemShop);
router.get("/system/rules", ...auth, c.getSystemRules);
router.post("/system/rules", ...auth, c.createSystemRule);
router.patch("/system/rules/:id", ...auth, c.updateSystemRule);
router.delete("/system/rules/:id", ...auth, c.deleteSystemRule);
module.exports = router;
